fix: sh compatibility
thislooksfun/snoots pull request #121
Opened 2023-05-12 18:32 UTC by cachho

this is a weird one. Husky wouldn't let me push. 

```
Linting commits before push...
.husky/pre-push: 7: Syntax error: "(" unexpected (expecting "done")
husky - pre-push hook exited with code 2 (error)
```

I did a little digging and found out that the array on line 7 isn't SH-shell compatible. 

With that being said, it returned the same error when I ran it with bash and fish.

This might very well be a me-problem, I have no idea. Anyways, I rewrote the line to use awk. I don't insist on the PR, I just want to share my fix. Thank you and have a nice weekend.

2023-05-12 22:30 UTC, thislooksfun commented
Weird, it works perfectly fine in both zsh and bash on my machine (macOS). In any case, more compatibility is (almost) always good, so thank you for the fix!

2023-05-12 22:33 UTC, thislooksfun requested changes

2023-05-12 22:33 UTC, thislooksfun commented on .husky/pre-push
>  set -e
Since this fix does not affect the produced package, please change the commit message to use either `chore:` or `ci:`.

2023-05-13 07:24 UTC, cachho commented on .husky/pre-push
>  set -e
done.

2023-05-13 19:43 UTC, thislooksfun approved these changes

2023-05-13 19:47 UTC, merged