feat: expose post media and listing options
thislooksfun/snoots pull request #55
Opened 2022-09-22 23:46 UTC by janvennemann

Hey,

first of all thanks for the great library. I'm using the Reddit API for a side project and this one has a much nicer API than the little outdated snoowrap.

I'm scanning Reddit for posts with media files, so i exposed and documented a couple of the media properties. Currently `mediaMetadata` covers all my needs.

In addition i needed to change the post listing methods like `getHotPosts` so they support the common options for listings. Some of them already had a single parameter, which i replaced with an options object so you are able to pass all available options. Since this library is currently still releasing with a `dev` pre-release tag i hope this breaking change is ok. Let me know if now and i try to figure a way around it.

BREAKING CHANGE: Changes the signature of all functions that return post listings to accept more options.

2022-09-23 01:56 UTC, thislooksfun commented
Thanks for the PR, and the interest in the project! I can't review this immediately, but I promise I will get to it soon! If I'm taking too long, please ping me again.

In the meantime, can you provide me with some example posts that have media? It'll be a lot faster for me to test if I don't have to find them myself. 😄

2022-09-23 17:41 UTC, janvennemann commented
> In the meantime, can you provide me with some example posts that have media? It'll be a lot faster for me to test if I don't have to find them myself. 😄

Sure! The `r/pics` subreddit usually has some posts that contain `mediaMetadata`. Here is small snippet to read some posts from the subreddit and display media info. This also demonstrates the new options object by using the `after` listing parameter.

```ts
import { Client, Post } from "snoots"

const client = new Client({
  userAgent: "snoots media test v1.0",
  creds: {
    clientId: process.env.CLIENT_ID!,
    clientSecret: process.env.CLIENT_SECRET!,
  },
})

/**
 * NOTES:
 *
 * Media items are either in `media` (Videos only?), `url` or `url_overridden_by_dest`
 * Multiple images have
 * - `gallery_data` (can include link to source, e.g. Tweet),
 * - `media_metadata` (reddit thumbnails images and original),
 * - `url` can point to the actual source or "reddit.com/gallery..."
 */
async function main() {
  const posts = await client.subreddits.getHotPosts("pics", { after: "t3_xl9m3t" })
  let counter = 0
  for await (const post of posts) {
    console.log(post.id, post.title, post.url, post.mediaMetadata)
    if (counter++ > 100) {
      break
    }
  }
}

main()
```

2022-09-25 21:35 UTC, thislooksfun requested changes
Thank you for identifying an area of snoots that is lacking and trying to fix it. However, one of the things I'm trying to do with snoots is to smooth out as many sharp edges as I can to make it easy and intuitive to use. Unfortunately sometimes (often) that means doing some extra work to make the developer experience easier. This includes things like using actual sensible names for parameters (see `PostData::body`, for example), and trying to guard against as many footguns as possible.

While this first draft has minimal changes (which is normally appreciated), that comes at the cost of leaving some of these sharp edges and footguns around. Before I am comfortable shipping this feature those will need to be cleaned up.

I am happy to perform the necessary refactoring if you would like (with credit, of course), or you can do it if you'd prefer, but either way it needs to be just a little cleaner first.

2022-09-25 21:35 UTC, thislooksfun commented on src/reddit/listing/listing.ts
> +  before?: string;
These should be made to be at least actually mutually exclusive. However there's also the issue that most listing types in snoots don't currently allow using `before`, only `after`, so if you manually use `before` it can get confused. Also the way you have set it up, manually specifying `after` here breaks the automatic pagination system.

Additionally these should be made more lenient by passing them through `BaseControls::namespace` (which should also be tweaked to check if the prefix is already there first) to allow passing just a post ID, not necessarily a fullname.

2022-09-25 21:35 UTC, thislooksfun commented on src/reddit/post/object.ts
> +  u: string;
These should be renamed to `width`, `height`, and `url`.

2022-09-25 21:35 UTC, thislooksfun commented on src/reddit/post/object.ts
> +  status: string;
This should be made into an enum, if possible.

2022-09-25 21:35 UTC, thislooksfun commented on src/reddit/post/object.ts
> +  s: ImageMetadata;
These should be renamed to describe what they actually are (`mediaType`, `mimeType`, etc.).

2022-09-25 21:35 UTC, thislooksfun commented on src/reddit/post/types.ts
> +  srDetail?: boolean;
Ideally this should be renamed to `expandSubreddits`

2022-09-25 21:35 UTC, thislooksfun commented on src/reddit/post/types.ts
> +  g?: string;
This should be renamed to `countryCode`

2022-09-25 21:35 UTC, thislooksfun commented on src/reddit/post/types.ts
> +  t?: TimeRange;
And this should be renamed to `timeRange`

2022-09-25 21:35 UTC, thislooksfun commented on src/reddit/subreddit/controls.ts
> +    options?: PostListingOptions<TSort>
Blindly passing the query options through to the listing system seems nice at first glance, but easily can lead to sharp edges between the user and snoots, and between snoots and the reddit API (see comments above about the `before` and `after` options.

2022-09-25 21:42 UTC, thislooksfun commented
@janvennemann Alright, I finally got around to finishing the first review.

---

Also, on an unrelated note, you don't have to `await` any API call that returns a `Listing` (not that there's any _harm_ in doing so, it's just not necessary). Creation of `Listing`s is synchronous. _Using_ them is asynchronous. So

```ts
const posts = await client.subreddits.getHotPosts("pics", { after: "t3_xl9m3t" })
```

can just be 

```ts
const posts = client.subreddits.getHotPosts("pics", { after: "t3_xl9m3t" })
```

2022-09-26 17:35 UTC, janvennemann commented
Thanks for the thorough review, i'll start working on those things right away.

> Also, on an unrelated note, you don't have to `await` any API call that returns a `Listing` (not that there's any _harm_ in doing so, it's just not necessary). Creation of `Listing`s is synchronous. _Using_ them is asynchronous.

Hm, looks like that `await` somehow snuck in to my sample code. I don't have it in other places ;)

2022-09-26 19:14 UTC, janvennemann commented
@thislooksfun I've implemented some of your suggestions, mainly the use of friendly names for the media properties and convert the raw reddit response to the new structure. A couple of other things you mentioned i left untouched for now, since i'm not entirely sure how to address them / how you'd like the API.

2022-09-26 19:53 UTC, janvennemann commented on src/reddit/listing/listing.ts
> +  before?: string;
I simply removed the `before` for now because i figured it doesn't make much sense to include it here when it's not currently allowed everywhere.

I looked at passing `after` through `BaseControls::namespace` but that doesn't work because the listing options will be set on `SubredditControls` which has a prefix of `r/` (should probably be `t5_`?) but the prefix needs to be `t3_`, which is what posts use.

2022-09-28 05:16 UTC, thislooksfun commented
@janvennemann Thanks for the update! I'll try to get to the re-review in the next few days if I can, but it might take a while since I'm currently out of town.

> A couple of other things you mentioned i left untouched for now, since i'm not entirely sure how to address them / how you'd like the API.

Heh, understandable. Wrangling the Reddit API into an intuitive package is a dark art that few should need to be subjected to (seriously the rest API is _so bad_). When I do my re-review I'll also take a crack at doing some of what I said myself and submit my own PR against this branch.

2023-01-08 12:29 UTC, JamesxX commented
Whats the state of this PR @thislooksfun , @janvennemann

2023-01-08 17:02 UTC, thislooksfun requested changes

2023-01-08 17:05 UTC, thislooksfun commented
@janvennemann Sorry for the delay, I completely lost motivation to work on this project for a while, but I'm back now! Could you please rebase and fix the conflicts + any new lint errors?

@JamesxX It still requires a bit of work before it can be merged, unfortunately.

2023-03-05 11:44 UTC, janvennemann commented on src/reddit/post/types.ts
> +  : [TSort] extends ["hot"]
For improved type suggestions when using it in `convertListingOptions(sort, options)` for example. It will now suggest the valid options depending on the `sort` parameter.

2023-03-06 17:58 UTC, janvennemann commented on src/reddit/post/controls.ts
> +    super(client, "t3_");
Hm, not sure why i changed this so i reverted it ;)

2023-03-06 18:00 UTC, janvennemann commented
@thislooksfun Alright, i finally had time to work on this again. I cleaned things up a little and addressed your comments.

2023-06-13 07:38 UTC, closed without merging